fix(pipeline): Austes nas variáveis de ambiente #5

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,19 +3,26 @@ name: CI/CD Docker Hub
 on:
   push:
     tags:
-      - '*' # O gatilho é qualquer tag, o filtro real está no 'if' abaixo
+      - '*' # Dispara em qualquer tag
 
 jobs:
   build-and-push:
     runs-on: ubuntu-latest
-    # SEU REGEX APLICADO AQUI:
-    if: |
-      contains(github.ref, 'refs/tags/') && 
-      matches(github.ref_name, '^(v|V)?([0-9]+\.)?([0-9]+\.)?(\*|[0-9]+).?(hf[0-9]+|Hf[0-9]+|HF[0-9]+)?$')
+    if: startsWith(github.ref, 'refs/tags/')
     
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
+
+      # Validação do seu Regex via Bash (Garante que só tags certas passem)
+      - name: Validate Tag Regex
+        run: |
+          TAG_NAME=${{ github.ref_name }}
+          REGEX="^(v|V)?([0-9]+\.)?([0-9]+\.)?(\*|[0-9]+).?(hf[0-9]+|Hf[0-9]+|HF[0-9]+)?$"
+          if [[ ! $TAG_NAME =~ $REGEX ]]; then
+            echo "Tag $TAG_NAME fora do padrão. Abortando build."
+            exit 1
+          fi
 
       - name: Login to Docker Hub
         uses: actions/docker-login-action@v3
@@ -31,10 +38,9 @@ jobs:
         with:
           context: .
           push: true
-          # Nome da sua imagem (Ex: usuario/laravel-app)
           tags: |
-            ${{ secrets.DOCKERHUB_USERNAME }}/seu-app-nome:${{ github.ref_name }}
-            ${{ secrets.DOCKERHUB_USERNAME }}/seu-app-nome:latest
-          # Otimização de build
+            ${{ secrets.DOCKERHUB_USERNAME }}/laravel-app:${{ github.ref_name }}
+            ${{ secrets.DOCKERHUB_USERNAME }}/laravel-app:latest
+          # Isso agiliza os builds futuros
           cache-from: type=gha
           cache-to: type=gha,mode=max
